/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  AddressLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../common";
import type { LUXSaleUtil, LUXSaleUtilInterface } from "../../src/LUXSaleUtil";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract LUXSale",
        name: "_sale",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "dailyTotals",
    outputs: [
      {
        internalType: "uint256[369]",
        name: "result",
        type: "uint256[369]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "sale",
    outputs: [
      {
        internalType: "contract LUXSale",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "unsoldTokens",
    outputs: [
      {
        internalType: "uint256[369]",
        name: "result",
        type: "uint256[369]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "userBuys",
    outputs: [
      {
        internalType: "uint256[369]",
        name: "result",
        type: "uint256[369]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506040516103b53803806103b58339818101604052602081101561003357600080fd5b5051600080546001600160a01b039092166001600160a01b0319909216919091179055610350806100656000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c806348d2df48146100515780636ad1fe02146100b057806383c56fc8146100d4578063b670a4b1146100dc575b600080fd5b6100776004803603602081101561006757600080fd5b50356001600160a01b03166100e4565b6040518082612e2080838360005b8381101561009d578181015183820152602001610085565b5050505090500191505060405180910390f35b6100b8610199565b604080516001600160a01b039092168252519081900360200190f35b6100776101a8565b610077610253565b6100ec6102fa565b60005b6101718110156101935760005460408051633904e1bf60e01b8152600481018490526001600160a01b03868116602483015291519190921691633904e1bf916044808301926020929190829003018186803b15801561014d57600080fd5b505afa158015610161573d6000803e3d6000fd5b505050506040513d602081101561017757600080fd5b50518282610171811061018657fe5b60200201526001016100ef565b50919050565b6000546001600160a01b031681565b6101b06102fa565b60005b61017181101561024f57600054604080516344e56d6360e11b81526004810184905290516001600160a01b03909216916389cadac691602480820192602092909190829003018186803b15801561020957600080fd5b505afa15801561021d573d6000803e3d6000fd5b505050506040513d602081101561023357600080fd5b50518282610171811061024257fe5b60200201526001016101b3565b5090565b61025b6102fa565b60005b61017181101561024f576000546040805163c83f42f760e01b81526004810184905290516001600160a01b039092169163c83f42f791602480820192602092909190829003018186803b1580156102b457600080fd5b505afa1580156102c8573d6000803e3d6000fd5b505050506040513d60208110156102de57600080fd5b5051828261017181106102ed57fe5b602002015260010161025e565b60405180612e20016040528061017190602082028036833750919291505056fea26469706673582212201273de58c630555ab6e5404bc576b7d3b1facfc90bbef7a008154c18d02f225b64736f6c63430007060033";

type LUXSaleUtilConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: LUXSaleUtilConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class LUXSaleUtil__factory extends ContractFactory {
  constructor(...args: LUXSaleUtilConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _sale: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(_sale, overrides || {});
  }
  override deploy(
    _sale: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(_sale, overrides || {}) as Promise<
      LUXSaleUtil & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): LUXSaleUtil__factory {
    return super.connect(runner) as LUXSaleUtil__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): LUXSaleUtilInterface {
    return new Interface(_abi) as LUXSaleUtilInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): LUXSaleUtil {
    return new Contract(address, _abi, runner) as unknown as LUXSaleUtil;
  }
}
