/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface SafeUserInterface extends Interface {
  getFunction(
    nameOrSignature: "addSafe" | "doConfirm" | "safe"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addSafe",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "doConfirm",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "safe", values?: undefined): string;

  decodeFunctionResult(functionFragment: "addSafe", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "doConfirm", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "safe", data: BytesLike): Result;
}

export interface SafeUser extends BaseContract {
  connect(runner?: ContractRunner | null): SafeUser;
  waitForDeployment(): Promise<this>;

  interface: SafeUserInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addSafe: TypedContractMethod<[_safe: AddressLike], [void], "nonpayable">;

  doConfirm: TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;

  safe: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addSafe"
  ): TypedContractMethod<[_safe: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "doConfirm"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "safe"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
