/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface TestUserInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "doBuy"
      | "doBuyWithLimit"
      | "doClaim"
      | "doExec"
      | "doFreeze"
      | "sale"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "doBuy", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "doBuyWithLimit",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "doClaim",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "doExec",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "doFreeze", values?: undefined): string;
  encodeFunctionData(functionFragment: "sale", values?: undefined): string;

  decodeFunctionResult(functionFragment: "doBuy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "doBuyWithLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "doClaim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "doExec", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "doFreeze", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sale", data: BytesLike): Result;
}

export interface TestUser extends BaseContract {
  connect(runner?: ContractRunner | null): TestUser;
  waitForDeployment(): Promise<this>;

  interface: TestUserInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  doBuy: TypedContractMethod<[wad: BigNumberish], [void], "payable">;

  doBuyWithLimit: TypedContractMethod<
    [wad: BigNumberish, window: BigNumberish, limit: BigNumberish],
    [void],
    "payable"
  >;

  doClaim: TypedContractMethod<[window: BigNumberish], [void], "nonpayable">;

  doExec: TypedContractMethod<[wad: BigNumberish], [void], "nonpayable">;

  doFreeze: TypedContractMethod<[], [void], "nonpayable">;

  sale: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "doBuy"
  ): TypedContractMethod<[wad: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "doBuyWithLimit"
  ): TypedContractMethod<
    [wad: BigNumberish, window: BigNumberish, limit: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "doClaim"
  ): TypedContractMethod<[window: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "doExec"
  ): TypedContractMethod<[wad: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "doFreeze"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sale"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
